title: SMShare
description: SMShare helps you keep record of your posts and share them on the internet.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/jerryOkafor/SMShare


# Color scheme supports "light" (default) and "dark"
color_scheme: dark
