name: Build SMS Share

on:
  push:
    branches:
      - main
    paths-ignore:
      - "Readme.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "Readme.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify_code_quality:
    name: Verify Code Quality
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decrypt large secret
        shell: bash
        run: |
          ./scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Setup Kotlin/Native compile(Konan) Cache
        if: always()
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/caches
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-macos-*
          key: ${{ runner.os }}-konan-${{ hashFiles('**/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Verify Code Quality
        run: ./gradlew detekt ktlintCheck

  build-ios:
    name: Build, Test iOS
    runs-on: macos-latest
    needs:
      - verify_code_quality
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decrypt large secret
        shell: bash
        run: |
          ./scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan

      - name: Install Dependencies
        run: |
          cd iosApp
          pod install --repo-update
        shell: bash

      - name: Build iOS app
        run: |
          xcodebuild \
          -workspace iosApp/iosApp.xcworkspace \
          -configuration Debug \
          -scheme iosApp \
          -sdk iphoneos \
          -allowProvisioningUpdates \
          -destination name='iPhone 16 Pro' build

      - name: Run iOS simulator Tests
        run: |
          ./gradlew :composeApp:iosSimulatorArm64Test :core:database:iosSimulatorArm64Test

  build-android:
    runs-on: macos-latest
    name: Build, Test Android
    needs:
      - verify_code_quality
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decrypt large secret
        shell: bash
        run: |
          ./scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan

      - name: Build
        run: ./gradlew :composeApp:assembleDebug

      - name: Run Android Unit tests
        run: |
          ./gradlew testDebugUnitTest

      - name: Generate Coverage Report
        run: |
          ./gradlew koverXMLReportDebug

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


  build-desktop:
    name: Build, Test Desktop
    runs-on: macos-latest
    needs:
      - verify_code_quality

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decrypt large secret
        shell: bash
        run: |
          ./scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan

      - name: Build
        run: ./gradlew :composeApp:desktopJar

      - name: Test Desktop
        run: |
          ./gradlew clean desktopTest
          
env:
  GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
#
#    # https://proandroiddev.com/optimising-ci-build-times-of-a-kotlin-multiplatform-project-2a430055f383